# Generated by Django 3.2.7 on 2021-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
            ],
        ),
    ]
